apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxap
spec:
  replicas: 1
  #strategy: # change here
    #type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default i                                                                                        s Recreate
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxserver
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: nginxapp-service
spec:
  selector:
    app: nginxapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31120


