version: '3.7'

services:
  admin:
    build:
      dockerfile: .  
      context: ./
    container_name: website
    
    ports:
      - '9500:80'

networks:
  default:
    external:
      name: nginx-proxy
