version: '3.7'

services:
  admin:
    build: 
      image: nhuongtrieu/app-nginx
      context: ./
      dockerfile: Dockerfile
    container_name: website
    
    ports:
      - '9500:80'

networks:
  default:
    external:
      name: nginx-proxy
